<?php

$config = new PhpCsFixer\Config();
$finder = PhpCsFixer\Finder::create()
	->exclude([
		'assets',
		'bin',
		'dist',
		'docs',
		'node_modules',
		'patches',
		'tests/stubs',
		'vendor',
	])
	->in(__DIR__);

return $config->setFinder( $finder )
	->setRiskyAllowed( true )
	->setIndent( "\t" )
	->setRules([
		'align_multiline_comment'                       => true,
		'array_indentation'                             => true,
		'array_syntax'                                  => [ 'syntax' => 'short' ],
		'backtick_to_shell_exec'                        => true,
		'cast_spaces'                                   => true,
		'combine_consecutive_issets'                    => true,
		'combine_consecutive_unsets'                    => true,
		'concat_space'                                  => [ 'spacing' => 'one'],
		'constant_case'                                 => true,
		'encoding'                                      => true,
		'full_opening_tag'                              => true,
		'increment_style'                               => [ 'style' => 'post' ],
		'line_ending'                                   => true,
		'logical_operators'                             => true,
		'lowercase_cast'                                => true,
		'lowercase_keywords'                            => true,
		'lowercase_static_reference'                    => true,
		'magic_constant_casing'                         => true,
		'magic_method_casing'                           => true,
		'multiline_comment_opening_closing'             => true,
		'native_function_casing'                        => true,
		'native_function_type_declaration_casing'       => true,
		'no_break_comment'                              => true,
		'no_closing_tag'                                => true,
		'no_empty_comment'                              => true,
		'no_empty_phpdoc'                               => true,
		'no_empty_statement'                            => true,
		'no_extra_blank_lines'                          => true,
		'no_homoglyph_names'                            => true,
		'no_leading_import_slash'                       => true,
		'no_leading_namespace_whitespace'               => true,
		'no_mixed_echo_print'                           => [ 'use' => 'echo' ],
		'no_null_property_initialization'               => true,
		'no_short_bool_cast'                            => true,
		'no_superfluous_elseif'                         => true,
		'no_trailing_comma_in_singleline_array'         => true,
		'no_trailing_whitespace'                        => true,
		'no_unset_cast'                                 => true,
		'no_unused_imports'                             => true,
		'no_useless_else'                               => true,
		'no_useless_return'                             => true,
		'no_whitespace_in_blank_line'                   => true,
		'non_printable_character'                       => true,
		'normalize_index_brace'                         => true,
		'not_operator_with_successor_space'             => true,
		'operator_linebreak'                            => true,
		'ordered_imports'                               => [ 'sort_algorithm' => 'alpha', 'imports_order'  => [ 'class', 'const', 'function' ] ],
		'phpdoc_align'                                  => true,
		'phpdoc_indent'                                 => true,
		'phpdoc_no_empty_return'                        => true,
		'phpdoc_scalar'                                 => true,
		'phpdoc_separation'                             => true,
		'phpdoc_summary'                                => true,
		'phpdoc_tag_casing'                             => true,
		'phpdoc_trim_consecutive_blank_line_separation' => true,
		'phpdoc_trim'                                   => true,
		'phpdoc_order'                                  => true,
		'psr_autoloading'                               => true,
		'short_scalar_cast'                             => true,
		'single_blank_line_at_eof'                      => true,
		'single_import_per_statement'                   => true,
		'single_line_after_imports'                     => true,
		'single_quote'                                  => [ 'strings_containing_single_quote_chars' => false ],
		'standardize_increment'                         => true,
		'standardize_not_equals'                        => true,
		'ternary_operator_spaces'                       => true,
		'whitespace_after_comma_in_array'               => true,
		'yoda_style'                                    => true,
	]);
